job:
permissions:
    id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
        contents: read
        steps:
            - name: Deploy to Deno Deploy
                uses: denoland/deployctl@v1
                    with:
                            project: discord-nodeify # the name of the project on Deno Deploy
                                    entrypoint: /src/index.js # the entrypoint to deploy
